// <auto-generated />
namespace Project_64131310.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ud4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ud4));
        
        string IMigrationMetadata.Id
        {
            get { return "202501090601363_ud4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
